matchtitle: TesseractUHC
deathban: false
uhc: true
ffa: true
announcementinterval: 20
nopvp: 300
nolatecomers: false
dragonmode: false
damagealerts: true
dropheads: true
noskeletons: false
killerbonus:
 id: 266
 quantity: 4
miningfatigue:
 gold: 0
 diamond: 0
hardstone: true
bonuschest:
- null
- null
- null
- null
- null
- null
- null
- null
- null
- null
- ==: org.bukkit.inventory.ItemStack
  type: BOW
  damage: 369
- ==: org.bukkit.inventory.ItemStack
  type: STONE_AXE
- ==: org.bukkit.inventory.ItemStack
  type: STONE_PICKAXE
- ==: org.bukkit.inventory.ItemStack
  type: WATCH
- ==: org.bukkit.inventory.ItemStack
  type: STONE_SPADE
- ==: org.bukkit.inventory.ItemStack
  type: STONE_SWORD
- ==: org.bukkit.inventory.ItemStack
  type: LEATHER_CHESTPLATE
- null
- null
- null
- null
- null
- null
- null
- null
- null
- null